package ru.ytkab0bp.beamklipper.service

// The tiny Python entry points each Chaquopy service writes next to the
// bundle it runs: Chaquopy calls main(), the real programs are scripts.
object BootstrapScripts {
    val KLIPPY: String = "import os\nimport importlib.util\nimport sys\n\ndef main():\n    here = os.path.dirname(os.path.abspath(__file__))\n    sys.path.insert(0, os.path.join(here, \"beam_ext\"))\n    sub = os.path.join(here, \"klippy\")\n    sys.path.insert(0, sub)\n    init = os.path.join(sub, \"__init__.py\")\n    if os.path.exists(init):\n        spec = importlib.util.spec_from_file_location(\"klippy\", init, submodule_search_locations=[sub])\n        m = importlib.util.module_from_spec(spec)\n        sys.modules[\"klippy\"] = m\n        spec.loader.exec_module(m)\n        from klippy.printer import main as _m\n        _m()\n    else:\n        entry = os.path.join(sub, \"klippy.py\")\n        spec = importlib.util.spec_from_file_location(\"klippy\", entry, submodule_search_locations=[sub])\n        m = importlib.util.module_from_spec(spec)\n        sys.modules[\"klippy\"] = m\n        spec.loader.exec_module(m)\n        if hasattr(m, \"main\"):\n            m.main()\n        else:\n            from klippy.printer import main as _m\n            _m()\n"

    val MOONRAKER: String = "import os\nimport importlib.util\nimport sys\n\ndef main():\n    here = os.path.dirname(os.path.abspath(__file__))\n    sys.path.insert(0, os.path.join(here, \"beam_ext\"))\n    sub = os.path.join(here, \"moonraker\")\n    sys.path.insert(0, sub)\n    init_py = os.path.join(sub, \"__init__.py\")\n    if os.path.isfile(init_py):\n        s1 = importlib.util.spec_from_file_location(\"moonraker\", init_py, submodule_search_locations=[sub])\n        m1 = importlib.util.module_from_spec(s1)\n        sys.modules[\"moonraker\"] = m1\n        s1.loader.exec_module(m1)\n    entry = os.path.join(sub, \"server.py\")\n    spec = importlib.util.spec_from_file_location(\"moonraker.server\", entry)\n    m = importlib.util.module_from_spec(spec)\n    sys.modules[\"moonraker.server\"] = m\n    if \"moonraker\" in sys.modules:\n        setattr(sys.modules[\"moonraker\"], \"server\", m)\n    spec.loader.exec_module(m)\n    m.main()\n"

    val OCTOEVERYWHERE: String = "import os\nimport sys\nimport runpy\n\ndef main():\n    here = os.path.dirname(os.path.abspath(__file__))\n    if here not in sys.path:\n        sys.path.insert(0, here)\n    runpy.run_module(\"moonraker_octoeverywhere\", run_name=\"__main__\", alter_sys=True)\n"

    val OBICO: String = "import os\nimport sys\nimport runpy\n\ndef main():\n    here = os.path.dirname(os.path.abspath(__file__))\n    if here not in sys.path:\n        sys.path.insert(0, here)\n    runpy.run_module(\"moonraker_obico.app\", run_name=\"__main__\", alter_sys=True)\n"
}
